export const DRONE_PRESETS = {
  mavic3e: {
    id: "mavic3e",
    name: "DJI Mavic 3 Enterprise · 4/3",
    platform: "multirotor",
    sensorWidthMm: 17.3,
    sensorHeightMm: 13,
    pixelsX: 5280,
    pixelsY: 3956,
    focalMm: null,
    focalChoices: [],
    maxSpeedMps: 15,
    planningSpeedMps: 10,
    maxFlightTimeMin: 45,
    usableFlightTimeMin: 32,
    turnRadiusM: 0,
    overlapAlong: 0.8,
    overlapAcross: 0.7,
    source: "https://enterprise.dji.com/mavic-3-enterprise/specs",
    note: "DJI указывает 24 мм как 35-мм эквивалент. Для строгого GSD введите физическое f из EXIF или калибровочного паспорта.",
  },
  matriceP1_35: {
    id: "matriceP1_35",
    name: "DJI Matrice 350 RTK · Zenmuse P1 35 мм",
    platform: "multirotor",
    sensorWidthMm: 35.9,
    sensorHeightMm: 24,
    pixelsX: 8192,
    pixelsY: 5460,
    focalMm: 35,
    focalChoices: [24, 35, 50],
    maxSpeedMps: 23,
    planningSpeedMps: 12,
    maxFlightTimeMin: 55,
    usableFlightTimeMin: 32,
    turnRadiusM: 0,
    overlapAlong: 0.8,
    overlapAcross: 0.7,
    source: "https://enterprise.dji.com/matrice-350-rtk/specs",
    note: "55 мин — паспортное время платформы без P1. Полезное время задано отдельно с резервом и должно уточняться по нагрузке и ветру.",
  },
  geoscanR4: {
    id: "geoscanR4",
    name: "Геоскан 201 Геодезия · Riebo R4 40 мм",
    platform: "fixedwing",
    sensorWidthMm: 36,
    sensorHeightMm: 24,
    pixelsX: 7952,
    pixelsY: 5304,
    focalMm: 40,
    focalChoices: [40],
    maxSpeedMps: 36.1,
    planningSpeedMps: 22,
    minSpeedMps: 17.8,
    maxFlightTimeMin: 180,
    usableFlightTimeMin: 135,
    turnRadiusM: 95,
    overlapAlong: 0.8,
    overlapAcross: 0.65,
    source: "https://www.geoscan.ru/ru/products/geoscan201/geo",
    note: "Растр зависит от комплектации камеры. Здесь 45-Мп класс 7952×5304; перед полётом замените его значением паспорта конкретной камеры.",
  },
  geoscanSony: {
    id: "geoscanSony",
    name: "Геоскан 201 · Sony RX1R II 35 мм",
    platform: "fixedwing",
    sensorWidthMm: 35.9,
    sensorHeightMm: 24,
    pixelsX: 7952,
    pixelsY: 5304,
    focalMm: 35,
    focalChoices: [35],
    maxSpeedMps: 36.1,
    planningSpeedMps: 22,
    minSpeedMps: 17.8,
    maxFlightTimeMin: 180,
    usableFlightTimeMin: 135,
    turnRadiusM: 95,
    overlapAlong: 0.8,
    overlapAcross: 0.65,
    source: "https://www.sony.com/electronics/support/compact-cameras-dsc-rx-series/dsc-rx1rm2/specifications",
    note: "Отдельная документированная камера 42,4 Мп. Время и скорость относятся к носителю и зависят от полезной нагрузки.",
  },
  ebeeSoda: {
    id: "ebeeSoda",
    name: "eBee X · S.O.D.A. 3D",
    platform: "fixedwing",
    sensorWidthMm: 13.2,
    sensorHeightMm: 8.8,
    pixelsX: 5472,
    pixelsY: 3648,
    focalMm: 10.6,
    focalChoices: [10.6],
    minSpeedMps: 11,
    maxSpeedMps: 30,
    planningSpeedMps: 18,
    maxFlightTimeMin: 90,
    usableFlightTimeMin: 68,
    turnRadiusM: 65,
    overlapAlong: 0.8,
    overlapAcross: 0.65,
    source: "https://www.sensefly.com/drone/ebee-x-fixed-wing-drone/",
    note: "До 90 мин — с endurance-батареей и совместимой камерой. S.O.D.A. использует глобальный затвор.",
  },
  custom: {
    id: "custom",
    name: "Пользовательский БВС + камера",
    platform: "multirotor",
    sensorWidthMm: 13.2,
    sensorHeightMm: 8.8,
    pixelsX: 5472,
    pixelsY: 3648,
    focalMm: 8.8,
    focalChoices: [],
    maxSpeedMps: 15,
    planningSpeedMps: 8,
    maxFlightTimeMin: 40,
    usableFlightTimeMin: 28,
    turnRadiusM: 0,
    overlapAlong: 0.8,
    overlapAcross: 0.65,
    source: "",
    note: "Введите параметры калиброванной камеры и эксплуатационные ограничения конкретного БВС.",
  },
};

export function pixelSizeMm(preset) {
  return preset.sensorWidthMm / preset.pixelsX;
}
